---
sidebar: sidebar 
permalink: install-setup/cable-hardware.html 
keywords: asa r2, aff a1k, aff a70, aff a90, aff c80, asa a1k, asa a90, asa a70, asa a30, asa a20, asa a50, asa c30 cable controllers 
summary: 'Câblez votre système de stockage ASA r2 pour permettre la communication du cluster, l"accès au réseau hôte, la connectivité de gestion et les connexions des baies de stockage.' 
---
= Branchez les câbles du matériel du système de stockage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Câblez votre système de stockage ASA r2 pour permettre la communication du cluster, l'accès au réseau hôte, la connectivité de gestion et les connexions des baies de stockage.



== Aperçu du câblage matériel

Le câblage diffère selon le modèle de plateforme, car chaque modèle ASA r2 possède des emplacements de slots, des affectations de ports et des configurations de modules d'E/S uniques. Sélectionnez la procédure correspondant à votre modèle ASA r2 :

* link:cable-hardware-a1k.html["Câble ASA A1K"]
* link:cable-hardware-a70-90.html["Câble ASA A70 et A90"]
* link:cable-hardware-a20-30-50.html["Câble ASA A20, A30 et A50"]
* link:cable-hardware-c30.html["Câble ASA C30"]


Lors du câblage matériel, vous effectuerez quatre types de connexions :

* *Connexions de cluster/HA*
+
Connectez les deux contrôleurs entre eux (cluster sans commutateur) ou à des commutateurs réseau de cluster (cluster avec commutateur). Ces connexions permettent la communication du cluster et le basculement haute disponibilité entre les paires de contrôleurs. Le trafic d’interconnexion de cluster et le trafic HA partagent les mêmes ports physiques.

* *Connexions réseau de l'hôte*
+
Connectez les contrôleurs aux hôtes SAN via Ethernet (iSCSI, NVMe/TCP) ou Fibre Channel (FC, NVMe/FC) selon la configuration de votre hôte. Ces connexions permettent l'accès aux données pour vos charges de travail de stockage.

* *Connexions réseau de gestion*
+
Connectez les contrôleurs à votre réseau de gestion pour accéder à l'administration système via ONTAP System Manager et CLI.

* *Connexions des étagères de stockage*
+
Connectez les contrôleurs aux étagères de stockage NS224 pour fournir une capacité de stockage à votre système.





== Ressources supplémentaires

Les procédures de câblage présentées illustrent les configurations courantes. Le câblage spécifique dépend des composants commandés pour votre système de stockage. Pour des informations complètes sur la configuration et la priorité des emplacements, consultez link:https://hwu.netapp.com["NetApp Hardware Universe"^].
