---
sidebar: sidebar 
permalink: install-setup/deploy-hardware.html 
keywords: asa r2, install hardware, deploy hardware, aff a1k, aff a70, aff a90, aff c80, asa a1k, asa a90, asa a70, asa a30, asa a20, asa a50, asa c30 
summary: 'Découvrez comment installer les kits de rails pour le système de stockage ASA r2 et les tiroirs de stockage, et sécuriser le matériel ASA r2 dans l"armoire ou le rack de télécommunications.' 
---
= Installez votre système de stockage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir préparé l'installation du système de stockage ASA r2, installez le matériel du système. Commencez par installer les kits de rails. Installez ensuite et sécurisez votre système de stockage dans une armoire ou un rack de télécommunications.

.Avant de commencer
* Assurez-vous de disposer des instructions fournies avec le kit de rails.
* Soyez conscient des problèmes de sécurité associés au poids du système de stockage et de l'étagère de stockage.
* Assurez-vous que le flux d'air qui traverse le système de stockage pénètre par l'avant où le cadre ou les embouts sont installés et sort par l'arrière où se trouvent les ports.


.Étapes
. Installez les kits de rails pour votre système de stockage et les étagères de stockage, selon les besoins, en suivant les instructions fournies avec les kits.
. Installez et sécurisez votre système de stockage dans l'armoire ou le rack de télécommunications :
+
.. Positionnez le système de stockage sur les rails au milieu de l'armoire ou du rack de télécommunications, puis soutenez le système de stockage par le bas et faites-le glisser pour le mettre en place.
.. Assurez-vous que les broches de guidage de l'armoire ou du rack Telco s'insèrent parfaitement dans les fentes de guidage du système de stockage.
.. Fixez le système de stockage à l'armoire ou au rack de télécommunications à l'aide des vis de montage fournies.


. Fixez le panneau à l'avant du système de stockage.
. Si votre système ASA r2 est fourni avec un dispositif de gestion des câbles, connectez-le à l'arrière du système de stockage.
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[Installez le périphérique de gestion des câbles]

. Installez et fixez le tiroir de stockage :
+
.. Placez l'arrière de la tablette de stockage sur les rails, puis soutenez la tablette par le bas et faites-la glisser dans l'armoire ou le rack de télécommunications.
+
Si vous installez plusieurs tiroirs de stockage, placez le premier tiroir de stockage directement au-dessus des contrôleurs. Placez le second tiroir de stockage directement sous les contrôleurs. Répétez cette procédure pour toutes les étagères de stockage supplémentaires.

.. Fixez l'étagère de stockage à l'armoire ou au rack de télécommunications à l'aide des vis de montage fournies.




.Et la suite ?
Après avoir installé le matériel de votre système ASA r2, vous link:cable-hardware.html["Reliez les contrôleurs et les tiroirs de stockage à votre système ASA r2"].
