---
sidebar: sidebar 
permalink: install-setup/set-up-data-access.html 
keywords:  
summary:  
---
= Activez l'accès aux données depuis des hôtes SAN vers votre système de stockage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour configurer l'accès aux données, vous devez vous assurer que les paramètres et paramètres critiques de votre client SAN pour un fonctionnement correct avec ONTAP sont configurés correctement. Si vous fournissez du stockage à votre environnement VMware, vous devez installer OTV 10.3 pour simplifier la gestion de votre stockage ASA r2.



== Configurez l'accès aux données à partir d'hôtes SAN

La configuration nécessaire pour configurer l'accès aux données sur votre système ASA r2 à partir de vos hôtes SAN varie en fonction du système d'exploitation hôte et du protocole. Une configuration correcte est importante pour de meilleures performances et un basculement réussi.

Reportez-vous à la documentation de l'hôte SAN ONTAP pour link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["Clients SCSI VMware vSphere"^] link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Clients NVMe VMware vSphere"^]et link:https://docs.netapp.com/us-en/ontap-sanhost/overview.html["Autres clients SAN"^] pour configurer correctement vos hôtes pour qu'ils se connectent à votre système ASA r2.



== Migrez des machines virtuelles VMware

Si vous devez migrer votre charge de travail de machine virtuelle d'un système de stockage ASA vers un système de stockage ASA r2, NetApp vous recommande d'utiliserlink:https://www.vmware.com/products/cloud-infrastructure/vsphere-foundation["VMware vSphere vMotion"^] pour effectuer une migration en direct et sans interruption de vos données.

Les unités de stockage ASA r2 sont provisionnées dynamiquement par défaut.  Lors de la migration de votre charge de travail VM, les disques virtuels (VMDK) doivent également être provisionnés de manière fine.

.Informations associées
* En savoir plus sur link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-why.html["les avantages de l'utilisation ONTAP pour vSphere"^] .
* En savoir plus surlink:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-srm-overview.html["Récupération de site VMware Live avec ONTAP"^] .
* En savoir plus surlink:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware_vmsc_overview.html#continuous-availability-solutions-for-vsphere-environments["solutions de disponibilité continue pour les environnements vSphere"^] .
* En savoir plus surlink:https://kb.netapp.com/on-prem/ontap/da/SAN/SAN-KBs/How_to_setup_Broadcom_VMware_ESXi_iSCSI_MPIO_with_ONTAP_SAN_ASA["Comment configurer Broadcom VMware ESXi iSCSI MPIO avec les systèmes de stockage ONTAP SAN ASA"^] .




== Migrer des données à partir d'un système de stockage tiers

À partir d' ONTAP 9.17.1, vous pouvez utiliser l'importation de LUN étrangers (FLI) pour migrer des données d'un LUN d'un système de stockage tiers vers un système ASA r2. L'utilisation de FLI pour la migration de vos données peut vous aider à réduire les risques de perte de données et d'interruption de service pendant le processus de migration.

FLI prend en charge les migrations en ligne et hors ligne. Lors d'une migration en ligne, le système client reste en ligne pendant la copie des données du système de stockage tiers vers le système de stockage ONTAP . Les migrations en ligne sont prises en charge par les systèmes d'exploitation hôtes Windows, Linux et ESXi. Lors d'une migration hors ligne, le système client est mis hors ligne, les données LUN sont copiées du système de stockage tiers vers le système de stockage ONTAP , puis le système client est remis en ligne.

* Apprenez à effectuer une link:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_offline_workflow.html["Migration hors ligne FLI"^] .
* Apprenez à effectuer une link:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_online_workflow.html["Migrations en ligne FLI"^] .




== Configurez votre système ASA r2 en tant que fournisseur de stockage dans votre environnement VMware

Vous pouvez utiliser les outils ONTAP pour VMware afin de mettre en place votre système ASA r2 en tant que fournisseur de stockage dans votre environnement VMware.

Les outils ONTAP pour VMware vSphere sont un ensemble d'outils compatibles avec VMware vCenter Server Virtual Appliance (vCSA) pour une gestion simplifiée des machines virtuelles sur vos hôtes VMware ESXi.

Les systèmes ASA r2 sont pris en charge par link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/concepts/ontap-tools-overview.html["Outils ONTAP pour VMware vSphere 10.3"^] et les versions ultérieures.

Découvrez comment link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["Déployez les outils ONTAP pour VMware"^]puis utilisez-le pour :

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["Ajouter des instances vCenter Server"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-esx-server-multipath-and-timeout-settings.html["Configurez les paramètres de l'hôte ESXi"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/discover-storage-systems-and-hosts.html["Découvrez votre système de stockage et vos hôtes ASA r2"^]


.Et la suite ?
Vous êtes prêt à link:../manage-data/provision-san-storage.html["provisionner le stockage"]permettre à vos hôtes SAN de lire et d'écrire des données sur les unités de stockage.
