---
sidebar: sidebar 
permalink: secure-data/migrate-encryption-keys-between-key-managers.html 
keywords: onboard key manager, external key manager, configure, migrate keys, store keys, authentication keys, encryption keys, asa r2 
summary: 'Vous pouvez utiliser le gestionnaire de clés intégré ONTAP sur votre système ASA r2 ou un gestionnaire de clés externe ou les deux (dans un cas) pour gérer les clés de chiffrement des données.' 
---
= Migrez les clés de chiffrement des données ONTAP entre les gestionnaires de clés sur les systèmes ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez gérer les clés de chiffrement des données avec le gestionnaire de clés intégré ONTAP de votre système ASA r2, un gestionnaire de clés externe, ou les deux dans des configurations prises en charge. Les gestionnaires de clés externes sont pris en charge uniquement au niveau de la machine virtuelle de stockage. Au niveau du cluster ONTAP, vous pouvez utiliser soit le gestionnaire de clés intégré, soit un gestionnaire de clés externe.

[cols="2,2"]
|===
| Si vous activez votre gestionnaire de clés sur... | Vous pouvez utiliser... 


| Au niveau du cluster uniquement  a| 
Gestionnaire de clés intégré ou gestionnaire de clés externe



| Niveau de machine virtuelle de stockage uniquement | Gestionnaire de clés externe uniquement 


 a| 
Le niveau de la machine virtuelle du cluster et du stockage
 a| 
Une des combinaisons de gestionnaire de clés suivantes :

* Option 1
+
Niveau cluster : gestionnaire de clés intégré

+
Niveau de la machine virtuelle de stockage : Gestionnaire de clés externe

* Option 2
+
Niveau cluster : gestionnaire de clés externe

+
Niveau de la machine virtuelle de stockage : Gestionnaire de clés externe



|===


[[migrate-keys-between-key-managers-at-the-ontap-cluster-level]]
== Migration des clés entre les gestionnaires de clés au niveau du cluster ONTAP

À partir de ONTAP 9.16.1, vous pouvez utiliser l'interface de ligne de commandes (CLI) d'ONTAP pour migrer des clés entre les gestionnaires de clés au niveau du cluster.

[role="tabbed-block"]
====
.Du gestionnaire de clés intégré au gestionnaire de clés externe
--
.Étapes
. Définissez le niveau de privilège sur avancé :
+
[source, cli]
----
set -privilege advanced
----
. Créez une configuration de gestionnaire de clés externe inactive :
+
[source, cli]
----
security key-manager external create-config
----
. Passer au gestionnaire de clés externe :
+
[source, cli]
----
security key-manager keystore enable -vserver <storage_vm_name> -type KMIP
----
. Supprimez la configuration du gestionnaire de clés intégré :
+
[source, cli]
----
security key-manager keystore delete-config -vserver <storage_vm_name> -type OKM
----
. Définissez le niveau de privilège sur admin :
+
[source, cli]
----
set -privilege admin
----


--
.Du gestionnaire de clés externe au gestionnaire de clés intégré
--
.Étapes
. Définissez le niveau de privilège sur avancé :
+
[source, cli]
----
set -privilege advanced
----
. Créez une configuration de gestionnaire de clés intégré inactive :
+
[source, cli]
----
security key-manager onboard create-config
----
. Activez la configuration du gestionnaire de clés intégré :
+
[source, cli]
----
security key-manager keystore enable -vserver <storage_vm_name> -type OKM
----
. Supprimez la configuration du gestionnaire de clés externe
+
[source, cli]
----
security key-manager keystore delete-config -vserver <storage_vm_name> -type KMIP
----
. Définissez le niveau de privilège sur admin :
+
[source, cli]
----
set -privilege admin
----


--
====


[[migrate-keys-between-key-managers-across-ontap-cluster-and-storage-vm-levels]]
== Migration des clés entre les gestionnaires de clés au niveau du cluster ONTAP et des VM de stockage

Vous pouvez utiliser l'interface de ligne de commandes (CLI) ONTAP pour migrer des clés entre les gestionnaires de clés aux niveaux du cluster et de la machine virtuelle de stockage.

.Étapes
. Définissez le niveau de privilège sur avancé :
+
[source, cli]
----
set -privilege advanced
----
. Migration des clés :
+
[source, cli]
----
security key-manager key migrate -from-vserver <storage_vm_name> -to-vserver <storage_vm_name>
----
. Définissez le niveau de privilège sur admin :
+
[source, cli]
----
set -privilege admin
----

