---
sidebar: sidebar 
permalink: secure-data/migrate-encryption-keys-between-key-managers.html 
keywords: onboard key manager, external key manager, configure, migrate keys, store keys, authentication keys, encryption keys, asa r2 
summary: 'Vous pouvez utiliser le gestionnaire de clés intégré ONTAP sur votre système ASA r2 ou un gestionnaire de clés externe ou les deux (dans un cas) pour gérer les clés de chiffrement des données.' 
---
= Migrez les clés de chiffrement des données ONTAP entre les gestionnaires de clés de votre système ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez gérer vos clés de chiffrement des données à l'aide du gestionnaire de clés intégré ONTAP sur votre système ASA r2 ou d'un gestionnaire de clés externe (ou les deux). Les gestionnaires de clés externes ne peuvent être activés qu'au niveau des VM de stockage. Au niveau du cluster ONTAP, vous pouvez activer le gestionnaire de clés intégré ou un gestionnaire de clés externe.

[cols="2,2"]
|===
| Si vous activez votre gestionnaire de clés sur... | Vous pouvez utiliser... 


| Au niveau du cluster uniquement  a| 
Gestionnaire de clés intégré ou gestionnaire de clés externe



| Niveau SVM uniquement | Gestionnaire de clés externe uniquement 


 a| 
Au niveau du cluster et du SVM
 a| 
Une des combinaisons de gestionnaire de clés suivantes :

* Option 1
+
Niveau cluster : gestionnaire de clés intégré

+
Niveau SVM : gestionnaire de clés externe

* Option 2
+
Niveau cluster : gestionnaire de clés externe

+
Niveau SVM : gestionnaire de clés externe



|===


== Migration des clés entre les gestionnaires de clés au niveau du cluster ONTAP

Depuis la version ONTAP 9.16.1, vous pouvez utiliser l'interface de ligne de commande ONTAP pour migrer les clés entre les gestionnaires de clés au niveau du cluster.

[role="tabbed-block"]
====
.De la carte intégrée à la carte externe
--
.Étapes
. Définissez le niveau de privilège sur avancé :
+
[source, cli]
----
set -privilege advanced
----
. Créez une configuration de gestionnaire de clés externe inactive :
+
[source, cli]
----
security key-manager external create-config
----
. Passer au gestionnaire de clés externe :
+
[source, cli]
----
security key-manager keystore enable -vserver <svm_name> -type KMIP
----
. Supprimez la configuration du gestionnaire de clés intégré :
+
[source, cli]
----
security key-manager keystore delete-config -vserver <svm_name> -type OKM
----
. Définissez le niveau de privilège sur admin :
+
[source, cli]
----
set -privilege admin
----


--
.De l'externe à l'embarqué
--
.Étapes
. Définissez le niveau de privilège sur avancé :
+
[source, cli]
----
set -privilege advanced
----
. Créez une configuration de gestionnaire de clés intégré inactive :
+
[source, cli]
----
security key-manager onboard create-config
----
. Activez la configuration du gestionnaire de clés intégré :
+
[source, cli]
----
security key-manager keystore enable -vserver <svm_name> -type OKM
----
. Supprimez la configuration du gestionnaire de clés externe
+
[source, cli]
----
security key-manager keystore delete-config -vserver <svm_name> -type KMIP
----
. Définissez le niveau de privilège sur admin :
+
[source, cli]
----
set -privilege admin
----


--
====


== Migration des clés entre les gestionnaires de clés au niveau du cluster ONTAP et des VM de stockage

Vous pouvez utiliser l'interface de ligne de commandes ONTAP pour migrer les clés entre le gestionnaire de clés au niveau du cluster et un gestionnaire de clés au niveau de la machine virtuelle de stockage.

.Étapes
. Définissez le niveau de privilège sur avancé :
+
[source, cli]
----
set -privilege advanced
----
. Migration des clés :
+
[source, cli]
----
security key-manager key migrate -from-vserver <svm_name> -to-vserver <svm_name>
----
. Définissez le niveau de privilège sur admin :
+
[source, cli]
----
set -privilege admin
----

