---
sidebar: sidebar 
permalink: secure-data/modify-arp-snapshot-retention-period.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, alerts, respond, warnings, security 
summary: Découvrez comment modifier les périodes de conservation des instantanés ARP en fonction de vos besoins de stockage et d’entreprise. 
---
= Modifier les périodes de conservation des snapshots ARP/AI sur les systèmes de stockage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la protection autonome contre les ransomwares avec intelligence artificielle (ARP/AI) détecte une activité anormale sur une ou plusieurs unités de stockage de votre système ASA r2, elle crée automatiquement un instantané ARP pour protéger les données. En fonction de votre capacité de stockage et de vos besoins métier, vous pouvez augmenter ou diminuer la période de rétention par défaut des instantanés ARP. Par exemple, vous pouvez augmenter la période de rétention pour les applications critiques afin de permettre des fenêtres de restauration des données plus longues, ou la diminuer pour les applications non critiques afin d'économiser de l'espace de stockage.

La période de conservation par défaut de l’instantané ARP varie en fonction de l’action que vous entreprenez en réponse à l’activité anormale.

[cols="2,2"]
|===
| Si vous effectuez cette action... | Les instantanés ARP sont conservés par défaut pendant... 


| Marquer comme faux positif | 12 heures 


| Marquer comme attaque potentielle par ransomware | 7 jours 


| Ne prenez pas de mesures immédiates | 10 jours 
|===
Vous pouvez modifier les périodes de conservation par défaut à l'aide de l'interface de ligne de commandes (CLI) ONTAP. Voir  https://docs.netapp.com/us-en/ontap/anti-ransomware/modify-automatic-snapshot-options-task.html["Modifier les options pour les instantanés automatiques ONTAP"] pour connaître les étapes permettant de modifier la période de conservation par défaut.
