---
sidebar: sidebar 
permalink: secure-data/pause-resume-anti-ransomware-protection.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, pause, resume, suspend 
summary: 'Si vous prévoyez un événement de charge de travail inhabituel, vous pouvez suspendre temporairement ARP avec analyse IA pour éviter les faux positifs lors de la détection d"attaques de ransomware' 
---
= Suspendre ou reprendre la protection ARP/AI sur les systèmes de stockage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir de ONTAP 9.17.1, vous pouvez utiliser la protection autonome contre les ransomwares avec intelligence artificielle (ARP/AI) pour protéger les données sur votre système ASA r2. Si vous prévoyez un événement de charge de travail inhabituel, vous pouvez suspendre temporairement l'analyse ARP/AI afin d'éviter les faux positifs. Une fois l'événement terminé, vous pouvez reprendre l'analyse ARP/AI.



[[pause-arpai]]
== Mettre en pause ARP/AI

Avant de déclencher un événement de charge de travail inhabituel, vous devrez peut-être suspendre temporairement l'analyse ARP/AI afin d'éviter les faux positifs.

.Étapes
. Dans System Manager, sélectionnez *Storage*.
. Sélectionnez les unités de stockage pour lesquelles vous souhaitez suspendre ARP/AI.
. Sélectionnez *Pause anti-ransomware*.


.Résultat
L'analyse ARP/AI est suspendue pour les unités de stockage sélectionnées et aucune activité suspecte ne vous est signalée dans le Gestionnaire système jusqu'à ce que vous repreniez ARP/AI.



[[resume-arpai]]
== Reprendre ARP/AI

Si vous suspendez ARP/AI pendant une charge de travail inhabituelle, reprenez-le une fois la charge de travail terminée afin de protéger vos données contre les attaques de ransomware.

.Étapes
. Dans System Manager, sélectionnez *Storage*.
. Sélectionnez les unités de stockage pour lesquelles vous souhaitez reprendre ARP/AI.
. Sélectionnez *Reprendre l'anti-ransomware*.


.Résultat
L’analyse des attaques potentielles de ransomware reprend et les activités suspectes vous sont signalées dans le Gestionnaire système.
