---
sidebar: sidebar 
permalink: secure-data/respond-anti-ransomware-protection-alerts.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, alerts, respond, warnings, security 
summary: Affichez les avertissements concernant les attaques potentielles de ransomware et prenez des mesures dans le Gestionnaire système. 
---
= Répondez aux alertes ARP/AI sur les systèmes de stockage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la protection autonome contre les ransomwares avec intelligence artificielle (ARP/AI) détecte une activité anormale sur une ou plusieurs unités de stockage de votre système ASA r2, System Manager affiche un avertissement sur le tableau de bord. Consultez l'avertissement, vérifiez l'activité et prenez des mesures si nécessaire pour protéger vos données.

Si un message d'avertissement ARP/AI s'affiche, utilisez l'outil de vérification d'intégrité des applications approprié pour contrôler les données sur l'unité de stockage avant d'entreprendre toute action. La vérification de l'intégrité des données de l'unité de stockage vous aide à déterminer si l'activité est acceptable ou s'il s'agit d'une attaque potentielle par rançongiciel.

[cols="2,2"]
|===
| Si l'activité anormale est... | Alors fais ceci... 


| Acceptable | Marquer l’activité comme un faux positif. 


| Une attaque potentielle de ransomware | Marquez l’activité comme une attaque potentielle de ransomware. 


| Indéterminé | N'agissez pas immédiatement. Surveillez l'unité de stockage pendant 7 jours maximum. Si l'unité de stockage continue de fonctionner normalement, marquez l'activité comme un faux positif. Si l'unité de stockage continue de présenter une activité anormale, marquez l'activité comme une attaque potentielle par rançongiciel. 
|===
.Étapes
. Dans System Manager, sélectionnez *Dashboard*.
+
Si ARP/AI a détecté une activité anormale sur une ou plusieurs unités de stockage, un message apparaît sous *Avertissements*.

. Sélectionnez le message d’avertissement.
. Sous *Aperçu des événements*, sélectionnez le message *Avertissements* qui indique le nombre d'unités de stockage présentant une activité anormale.
. Sous *Unités de stockage avec activité anormale*, sélectionnez l'unité de stockage.
. Sélectionnez *Sécurité*.
+
S'il y a une activité anormale sur l'unité de stockage, un message s'affiche sous *Anti-ransomware*.

. Sélectionnez *Choisir une action*.
. Sélectionnez *Marquer comme faux positif* ou sélectionnez *Marquer comme attaque potentielle par ransomware*.


.Et la suite ?
Si vous constatez des pics d'activité dans votre unité de stockage, qu'il s'agisse de pics ponctuels ou d'une augmentation caractéristique d'une nouvelle norme, vous devez les signaler comme étant sans danger. Le signalement manuel de ces pics comme étant sans danger contribue à améliorer la précision des évaluations des menaces d'ARP. Découvrez comment link:https://docs.netapp.com/us-en/ontap/anti-ransomware/manage-parameters-task.html#report-known-surges["signaler les pics connus d'ARP/IA"^].
