---
sidebar: sidebar 
permalink: learn-more/hardware-comparison.html 
keywords: compare asa r2, asa a1k, asa a70, asa a90 
summary: 'Les systèmes ASA proposent un support matériel optimisé pour les solutions SAN uniquement. Les systèmes ASA r2 permettent d"optimiser le matériel et les logiciels.' 
searchtitle: Comparez les systèmes ASA r2 aux autres systèmes ONTAP 
---
= Comparez les systèmes ASA r2 aux autres systèmes ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes ASA r2 offrent une solution matérielle et logicielle unifiée pour les environnements SAN et basée sur des plateformes 100 % Flash. Les systèmes ASA r2 sont différents des autres systèmes ONTAP (ASA, AFF et FAS) lors de l'implémentation de la couche de stockage, des protocoles pris en charge et des fonctions ONTAP.

Sur un système ASA r2, le logiciel ONTAP est optimisé pour prendre en charge les fonctionnalités SAN essentielles, tout en limitant la visibilité et la disponibilité des fonctionnalités non liées à SAN. Par exemple, System Manager exécuté sur un système ASA r2 n'affiche pas les options permettant de créer des répertoires locaux pour les clients NAS. Cette version simplifiée de ONTAP est identifiée comme la personnalité _ASA r2_. ONTAP s'exécutant sur tous les autres systèmes ONTAP (ASA, AFF, FAS) est identifié comme _personnalité ONTAP unifiée_. Les différences entre les personnalités ONTAP sont référencées dans la référence de commande ONTAP (pages man), la spécification de l'API REST et les messages EMS, le cas échéant.

Vous pouvez vérifier le profil de votre stockage ONTAP dans System Manager ou via l'interface de ligne de commande ONTAP.

* Dans le menu System Manager, sélectionnez *Cluster > Présentation*.
* Dans l'interface de ligne de commande, entrez : `san config show`


Impossible de modifier le profil de votre système de stockage ONTAP.

La couche de stockage des systèmes ONTAP exécutant la fonction ONTAP unifiée utilise des agrégats comme unité de stockage de base. Un agrégat possède un jeu spécifique des disques disponibles dans un système de stockage. L'agrégat alloue de l'espace sur les disques qu'il possède aux volumes pour les LUN et les espaces de noms. Un utilisateur de ONTAP unifié peut utiliser l'interface de ligne de commande pour créer et modifier des agrégats, des volumes, des LUN et des espaces de noms.

Dans les systèmes ASA r2, la couche stockage remplace les agrégats par une zone de disponibilité du stockage. Une zone de disponibilité de stockage est un pool de stockage commun qui a accès à tous les disques disponibles dans le système de stockage. La zone de disponibilité du stockage est visible pour les deux nœuds d'une paire HA ASA r2. Lorsqu'une unité de stockage (basée sur un LUN ou un namespace NVMe) est créée, ONTAP crée automatiquement un volume contenant une machine virtuelle de stockage (VM) dans la zone de disponibilité du stockage pour héberger l'unité de stockage. Grâce à cette approche automatisée et simplifiée de la gestion du stockage, certaines options System Manager, commandes ONTAP et terminaux d'API REST ne sont pas disponibles ou sont utilisées de façon limitée sur un système ASA r2. Par exemple, comme la création et la gestion de volumes sont automatisées pour les systèmes ASA r2, le menu *volumes* n'apparaît pas dans le Gestionnaire système et la `volume create` commande n'est pas prise en charge.

Comparatif de ASA r2 avec les autres systèmes de stockage ONTAP :

[cols="1h,2,2,2,2"]
|===
|  | ASA r2 | ASA | AFF | FAS 


 a| 
*Personnalité ONTAP*
| ASA r2 | ASA | Unifiée | Unifiée 


 a| 
*Prise en charge du protocole SAN*
| Oui | Oui | Oui | Oui 


 a| 
*Prise en charge du protocole NAS*
| Non | Non | Oui | Oui 


 a| 
*Prise en charge de la couche de stockage*
| Zone de disponibilité du stockage | 64 bits | 64 bits | 64 bits 
|===
Les plateformes ASA suivantes sont classées en tant que systèmes ASA r2 :

* ASA A1K
* ASA A70
* ASA A90


.Pour en savoir plus
* En savoir plus sur link:https://docs.netapp.com/us-en/ontap-systems-family/intro-family.html["Systèmes matériels ONTAP"^].
* Consultez la prise en charge complète de la configuration et les limites des systèmes ASA et ASA r2 dans link:https://hwu.netapp.com/["NetApp Hardware Universe"^].
* En savoir plus sur link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"^]le .




== Récapitulatif des différences entre les systèmes ASA r2

Les principales différences entre les systèmes ASA r2 et FAS, AFF et ASA concernant l'interface de ligne de commande et l'API REST de ONTAP sont décrites ci-dessous.

.Création de SVM par défaut avec services de protocole
Les nouveaux clusters contiennent automatiquement un SVM de données par défaut lorsque les protocoles SAN sont activés. Les LIF de données IP prennent en charge les protocoles iSCSI et NVMe/TCP et utilisent la `default-data-blocks` stratégie de service par défaut.

.Création automatique de volume
La création d'une unité de stockage (LUN ou espace de noms) crée automatiquement un volume à partir de la zone de disponibilité du stockage. Il en résulte un namespace commun et simplifié. La suppression d'une unité de stockage supprime automatiquement le volume associé.

.Modifications du provisionnement fin et lourd
Les unités de stockage sont toujours à provisionnement fin sur les systèmes de stockage ASA r2. Le provisionnement lourd n'est pas pris en charge.
