---
sidebar: sidebar 
permalink: learn-more/software-support-limitations.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa, a50, asa a30, asa a20, asa c30, unsupported features 
summary: Bien que les systèmes ASA r2 proposent une prise en charge étendue des solutions SAN, certaines fonctionnalités du logiciel ONTAP ne sont pas prises en charge. 
---
= Limitations et prise en charge du logiciel ONTAP pour les systèmes de stockage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bien que les systèmes ASA r2 proposent une prise en charge étendue des solutions SAN, certaines fonctionnalités du logiciel ONTAP ne sont pas prises en charge.

.Les systèmes ASA r2 ne prennent pas en charge les éléments suivants :
* FabricPool
* Provisionnement lourd des LUN
* MetroCluster
* Chiffrement d'agrégat NetApp (NAE)
* Protocoles d'objet
* API ONTAP S3 SnapMirror et S3
* SnapLock
+
SnapLock Compliance et Enterprise ne sont pas pris en charge sur les clusters principaux dans les environnements SAN. SnapLock pour SnapVault est pris en charge sur les clusters secondaires.

* La réplication SnapMirror est prise en charge sur les systèmes ASA r2 avec les limitations suivantes :
+
** La réplication synchrone SnapMirror n'est pas prise en charge.
** La réplication asynchrone SnapMirror est prise en charge uniquement entre deux systèmes ASA r2. La réplication asynchrone SnapMirror n'est pas prise en charge entre un système ASA r2 et un système ASA, AFF ou FAS ou le cloud.
+
En savoir plus surlink:../data-protection/pre-defined-protection-policies.html["Les politiques de réplication SnapMirror sont prises en charge sur les systèmes ASA r2."] .

** La synchronisation active SnapMirror est prise en charge uniquement entre deux systèmes ASA r2.
+
En savoir plus surlink:../data-protection/snapmirror-active-sync.html["Synchronisation active SnapMirror sur les systèmes ASA r2"] .





.Les systèmes ASA r2 prennent en charge les éléments suivants :
* Chiffrement double couche
+
Les systèmes ASA r2 prennent en charge le chiffrement matériel à l'aide de disques à chiffrement automatique (SED) et le chiffrement logiciel à l'aide de la technologie NetApp Volume Encryption (NVE). link:../secure-data/encrypt-data-at-rest.html["Découvrez comment appliquer le chiffrement double couche"] des données sur votre système ASA r2.



.Pour en savoir plus
* link:https://hwu.netapp.com/["NetApp Hardware Universe"^]Pour plus d'informations sur la prise en charge matérielle et les limitations de ASA r2, reportez-vous au.

