---
sidebar: sidebar 
permalink: manage-data/migrate-svm.html 
keywords: move svm, migrate svm, asa, asa r2, storage vm, storage virtual machine 
summary: 'Si l"espace d"une zone de disponibilité du stockage est insuffisant, vous pouvez déplacer des unités de stockage vers une autre zone de disponibilité du stockage afin d"équilibrer l"utilisation du stockage dans le cluster.' 
---
= Migrer une machine virtuelle de stockage d'un cluster ASA vers un cluster ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir d' ONTAP 9.18.1, vous pouvez migrer sans interruption une machine virtuelle de stockage (VM) de n'importe quel cluster ASA vers n'importe quel cluster ASA r2.  La migration d'un cluster ASA vers un cluster ASA r2 vous permet d'adopter l'architecture simplifiée et rationalisée des systèmes ASA r2 pour les environnements SAN uniquement.

La migration des machines virtuelles de stockage entre les systèmes de stockage ASA et ASA r2 est prise en charge comme suit :

[cols="2"]
|===
| À partir de l'un des systèmes ASA suivants : | À l'un des systèmes ASA r2 suivants : 


 a| 
* ASA C800
* ASA C400
* ASA C250
* ASA A900
* ASA A800
* ASA A400
* ASA A250
* ASA A150
* ASA AFF A800
* ASA AFF A700
* ASA AFF A400
* ASA AFF A250
* ASA AFF A220

 a| 
* ASA A1K
* ASA C30
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20


|===

NOTE: Pour obtenir la liste la plus récente des systèmes ASA et ASA r2, consultezlink:https://hwu.netapp.com/["NetApp Hardware Universe"^] .  Les systèmes ASA r2 sont répertoriés dans NetApp Hardware Universe sous le nom de «ASA série A/série C (nouveau) ».

Vous pouvez migrer une machine virtuelle de stockage vers un cluster ASA r2 uniquement à partir d'un cluster ASA .  La migration depuis tout autre type de système ONTAP n'est pas prise en charge.

.Avant de commencer
Tous les nœuds du cluster ASA r2 et du cluster ASA doivent exécuter ONTAP 9.18.1 ou une version ultérieure.  Les versions des correctifs ONTAP 9.18.1 sur les nœuds du cluster peuvent varier.



== Étape 1 : Vérifier l’état de la machine virtuelle de stockage ASA

Avant de migrer une VM de stockage depuis un système ASA , aucun espace de noms NVMe ni vVols ne doit être présent et chaque volume de la VM de stockage ne doit contenir qu'un seul LUN.  La migration des espaces de noms NVMe et des vVols n'est pas prise en charge.  L'architecture des systèmes ASA r2 exige que les volumes contiennent un seul LUN.

.Étapes
. Vérifiez qu'aucun espace de noms NVMe n'est présent dans la machine virtuelle de stockage :
+
[source, cli]
----
vserver nvme namespace show -vserver <storage_VM>
----
+
Si des entrées sont affichées, les objets NVMe doivent êtrelink:https://docs.netapp.com/us-en/ontap/nvme/convert-namespace-to-lun-task.html["converti"^] aux LUN ou supprimés.  Voir le `vserver nvme namespace delete` et le `vserver nvme subsystem delete` commandes dans lelink:https://docs.netapp.com/us-en/ontap/concepts/manual-pages.html["Référence des commandes ONTAP"^] pour plus d'informations.

. Vérifiez qu'aucun vVols n'est présent dans la machine virtuelle de stockage :
+
[source, cli]
----
lun show -verser <storage_VM> -class protocol-endpoint,vvol
----
+
Si des vVols sont présents, ils doivent être copiés sur une autre machine virtuelle de stockage, puis supprimés de la machine virtuelle de stockage à migrer.  Voir le `lun copy` et `lun delete` commandes dans lelink:https://docs.netapp.com/us-en/ontap/concepts/manual-pages.html["Référence des commandes ONTAP"^] pour plus d'informations.

. Vérifiez que chaque volume de la machine virtuelle de stockage contient un seul LUN :
+
[source, cli]
----
lun show -verser <storage_VM>
----
+
Si un volume contient plusieurs LUN, utilisez le `volume create` et `lun move` commandes pour créer un ratio volume/LUN de 1:1. Voir lelink:https://docs.netapp.com/us-en/ontap/concepts/manual-pages.html["Référence des commandes ONTAP"^] pour plus d'informations.



.Et la suite ?
Vous êtes prêt à créer une relation de pair à pair entre vos clusters ASA et ASA r2.



== Étape 2 : Créez une relation de pair à pair entre vos clusters ASA et ASA r2

Avant de pouvoir migrer une machine virtuelle de stockage d'un cluster ASA vers un cluster ASA r2, vous devez créer une relation de pair à pair.  Une relation d'égal à égal définit les connexions réseau qui permettent aux clusters ONTAP et aux machines virtuelles de stockage d'échanger des données en toute sécurité.

.Avant de commencer
Vous devez avoir créé des LIF inter-clusters sur chaque nœud des clusters appariés en utilisant l'une des méthodes suivantes.

* link:https://docs.netapp.com/us-en/ontap/peering/configure-intercluster-lifs-share-data-ports-task.html["Configurer les LIF inter-clusters sur les ports de données partagés"^]
* link:https://docs.netapp.com/us-en/ontap/peering/configure-intercluster-lifs-use-dedicated-ports-task.html["Configurez les LIF inter-clusters sur des ports de données dédiés"^]
* link:https://docs.netapp.com/us-en/ontap/peering/configure-intercluster-lifs-use-ports-own-networks-task.html["Configurer les LIF inter-clusters dans des espaces IP personnalisés"^]


.Étapes
. Sur le cluster ASA r2, créez une relation de pair avec le cluster ASA et générez une phrase secrète :
+
[source, cli]
----
cluster peer create -peer-addrs <ASA_cluster_LIF_IPs> -generate-passphrase
----
+
L'exemple suivant crée une relation d'homologue entre le cluster 1 et le cluster 2 et crée une phrase secrète générée par le système :

+
[listing]
----
cluster1::> cluster peer create -peer-addrs 10.98.191.193 -generate-passphrase
Passphrase: UCa+6lRVICXeL/gq1WrK7ShR
            Peer Cluster Name: cluster2
            Initial Allowed Vserver Peers: -
            Expiration Time: 6/7/2017 09:16:10 +5:30
            Intercluster LIF IP: 10.140.106.185
Warning: make a note of the passphrase - it cannot be displayed again.

----
. Copiez la phrase secrète générée.
. Sur le cluster ASA , créez une relation de pair avec le cluster ASA r2 :
+
[source, cli]
----
cluster peer create -peer-addrs <ASA_r2_LIF_IPs>
----
. Saisissez la phrase secrète générée sur le cluster ASA r2.
. Vérifiez que la relation entre pairs du cluster est bien créée :
+
[source, cli]
----
cluster peer show
----
+
L'exemple suivant illustre le résultat attendu pour des clusters appariés avec succès.

+
[listing]
----
cluster1::> cluster peer show

Peer Cluster Name   Cluster Serial Number   Availability   Authentication
-----------------   ---------------------   -------------- --------------
cluster2             1-80-123456             Available      ok
----


.Résultat
Les clusters ASA et ASA r2 sont appariés et les données des machines virtuelles de stockage peuvent être transférées en toute sécurité.

.Et la suite ?
Vous êtes prêt à préparer votre machine virtuelle de stockage ASA pour la migration.



== Étape 3 : Préparer la migration des machines virtuelles de stockage d’un ASA vers un cluster ASA r2

Avant de migrer une machine virtuelle de stockage (VM) d'un cluster ASA vers un cluster ASA r2, vous devez effectuer une vérification préalable de la migration et corriger les problèmes éventuels.  Vous ne pouvez pas effectuer la migration tant que la vérification préalable n'a pas été réussie.

.Étape
. Depuis votre cluster ASA r2, exécutez la vérification préalable de la migration :
+
[source, cli]
----
vserver migrate start -vserver <storage_VM> -source-cluster <asa_cluster> -check-only true
----
+
Si vous devez résoudre des problèmes pour préparer votre cluster ASA à la migration, le problème et la solution corrective sont affichés.  Corrigez le problème et répétez la vérification préalable jusqu'à ce qu'elle se termine avec succès.



.Et la suite ?
Vous êtes prêt à migrer votre machine virtuelle de stockage de votre cluster ASA vers un cluster ASA r2.



== Étape 4 : Migrer une machine virtuelle de stockage ASA vers un cluster ASA r2

Une fois votre cluster ASA préparé et la relation de pair de cluster nécessaire créée avec le cluster ASA r2, vous pouvez commencer la migration de la VM de stockage.

Lors de la migration d'une machine virtuelle de stockage, il est recommandé de laisser une marge de 30 % sur le processeur, tant sur le cluster ASA que sur le cluster ASA r2, afin de permettre l'exécution de la charge de travail du processeur.

.Description de la tâche
Après la migration de la machine virtuelle de stockage, les clients sont automatiquement basculés vers le cluster ASA r2 et la machine virtuelle de stockage sur le cluster ASA est automatiquement supprimée.  La bascule automatique et la suppression automatique des machines virtuelles de stockage sont activées par défaut.  Vous pouvez également les désactiver tous les deux et effectuer manuellement la bascule et la suppression de la machine virtuelle de stockage.

.Avant de commencer
* Le cluster ASA r2 doit disposer d'un espace libre suffisant pour accueillir la machine virtuelle de stockage migrée.
* Si la machine virtuelle de stockage ASA contient des volumes chiffrés, le gestionnaire de clés intégré ou le gestionnaire de clés externe du système ASA r2 doit être configuré au niveau du cluster.
* Les opérations suivantes ne peuvent pas être exécutées sur le cluster ASA source :
+
** Opérations de basculement
** WAFLIRON
** Empreinte digitale
** Déplacement de volume, réhébergement, clonage, création, conversion ou analyse




.Étapes
. Depuis le cluster ASA r2, lancez la migration de la machine virtuelle de stockage :
+
[source, cli]
----
vserver migrate start -vserver <storage_VM_name> -source-cluster <ASA_cluster>
----
+
Pour désactiver la bascule automatique, utilisez le `-auto-cutover false` paramètre.  Pour désactiver la suppression automatique de la machine virtuelle de stockage ASA , utilisez le `-auto-source-cleanup false` paramètre.

. Surveillez l'état de la migration
+
[source, cli]
----
vserver migrate show -vserver <storage_VM_name>
----
+
Une fois la migration terminée, le *statut* s'affiche comme *migration-terminée*.




NOTE: Si vous devez suspendre ou annuler la migration avant le début du basculement automatique, utilisez la `vserver migrate pause` et le `vserver migrate abort` commandes.  Vous devez suspendre la migration avant de l'annuler.  Vous ne pouvez pas annuler la migration une fois la transition commencée.

.Résultat
La machine virtuelle de stockage est migrée du cluster ASA vers le cluster ASA r2.  Le nom et l'UUID de la machine virtuelle de stockage, le nom de l'interface logique de données, l'adresse IP et les noms des objets, tels que le nom du volume, restent inchangés.  L'UUID des objets migrés dans la machine virtuelle de stockage est mis à jour.

.Et la suite ?
Si vous avez désactivé la bascule automatique et la suppression automatique des machines virtuelles de stockage,link:svm-post-migrate-cutover-cleanup.html["Basculez manuellement vos clients ASA vers votre cluster ASA r2 et supprimez la machine virtuelle de stockage du cluster ASA."] .
