---
sidebar: sidebar 
permalink: monitor/monitor-storage.html 
keywords: monitor, storage, cluster, utilization, usage 
summary: 'Surveillez l"utilisation de votre stockage pour vous assurer de disposer de la capacité de stockage dont vous avez besoin pour gérer vos charges de travail actuelles et futures.' 
searchtitle: 'Surveillez l"utilisation de l"espace à l"aide de ONTAP System Manager | ASA r2' 
---
= Surveillez l'utilisation du cluster et des unités de stockage sur les systèmes de stockage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilisez ONTAP System Manager pour surveiller l'utilisation du stockage et vous assurer que vous disposez de la capacité de stockage nécessaire pour gérer vos charges de travail actuelles et futures.



== Surveillance de l'utilisation du cluster

Surveillez régulièrement la quantité de stockage consommée par votre cluster afin de vous assurer que, si nécessaire, vous êtes prêt à étendre la capacité du cluster avant de manquer d'espace.

.Étapes
. Dans System Manager, sélectionnez *Dashboard*.
. Sous *capacité*, affichez la quantité d'espace physique utilisé et la quantité d'espace disponible sur votre cluster.
+
Le taux de réduction des données représente l'espace économisé grâce à l'efficacité du stockage.



.Et la suite ?
Si l'espace de votre cluster est insuffisant ou s'il ne dispose pas de la capacité nécessaire pour répondre à un nouveau besoin, envisagez d'link:../administer/increase-storage-capacity.html["ajouter de nouveaux lecteurs"]augmenter votre capacité de stockage avec votre système ASA r2.



== Surveiller l'utilisation de la zone de disponibilité du stockage

Chaque paire haute disponibilité d'un système ASA r2 utilise un pool de stockage commun appelé _zone de disponibilité du stockage_. La zone de disponibilité du stockage a accès à tous les disques disponibles dans le système de stockage et est visible pour les deux nœuds de la paire haute disponibilité.

Si votre cluster comporte 4 nœuds ou plus, vous pouvez afficher la quantité d'espace utilisée par la zone de disponibilité du stockage pour chaque paire haute disponibilité. Cette métrique n'est pas disponible pour les clusters à 2 nœuds.

.Étapes
. Dans System Manager, sélectionnez *Cluster*, puis *Présentation*.
+
Un récapitulatif de l'utilisation de la zone de disponibilité du stockage s'affiche pour chaque paire HA dans le cluster.

. Si vous souhaitez obtenir des mesures plus détaillées, sélectionnez une disponibilité spécifique du stockage.
+
Sous *vue d'ensemble*, la capacité de la zone de disponibilité du stockage, la quantité d'espace utilisé et le taux de réduction des données sont affichés.

+
Sous *unités de stockage*, une liste de toutes les unités de stockage de la zone de disponibilité de stockage s'affiche.



.Et la suite ?
Si le niveau d'espace de votre zone de disponibilité du stockage est faible, envisagez link:../manage-data/move-storage-units.html["déplacer les unités de stockage"]d'utiliser une autre zone de disponibilité du stockage pour équilibrer l'utilisation du stockage dans le cluster.



== Surveiller l'utilisation de l'unité de stockage

Surveillez la quantité de stockage consommée par une unité de stockage afin d'augmenter de manière proactive la taille de l'unité de stockage en fonction des besoins de votre entreprise.

.Étapes
. Dans System Manager, sélectionnez *Storage*.
. Sélectionnez l'unité de stockage que vous souhaitez surveiller, puis sélectionnez *Présentation*.
. Sous *stockage*, affichez ce qui suit :
+
** Taille de votre unité de stockage
** Quantité d'espace utilisé
** Ratio de réduction de données
+
Le taux de réduction des données représente l'espace économisé grâce à l'efficacité du stockage

** Snapshot utilisé
+
Snapshot utilisé représente la quantité de stockage utilisée par les snapshots.





.Et la suite ?
Si votre unité de stockage approche de link:../manage-data/modify-storage-units.html["modifier l'unité de stockage"]sa capacité, vous devez augmenter sa taille.
