---
sidebar: sidebar 
permalink: administer/rebalance-workloads.html 
keywords: rebalance workload, workload rebalancing, node balancing, asa r2 
summary: 'À partir d" ONTAP 9.17.1, ONTAP rééquilibre automatiquement les charges de travail entre les nœuds d"une paire HA système ASA r2 pour des performances optimales.' 
---
= Rééquilibrer les charges de travail entre les nœuds sur les systèmes de stockage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir d' ONTAP 9.17.1, ONTAP rééquilibre automatiquement les charges de travail entre les nœuds d'une paire de systèmes HA ASA r2 pour des performances optimales. Par exemple, si l'utilisation de l'espace sur un nœud augmente à 70 % alors que l'utilisation sur son partenaire HA n'est que de 30 %, ONTAP déplace automatiquement les charges de travail afin que l'utilisation de l'espace de chaque nœud soit plus étroitement adaptée. Comme les nœuds de la paire HA partagent la même zone de disponibilité de stockage, le rééquilibrage des charges de travail est une opération sans copie et sans impact sur les performances.



== Modifier la période d'évaluation par défaut pour le rééquilibrage automatique de la charge de travail

Le rééquilibrage automatique de la charge de travail est activé par défaut 14 jours après la mise à niveau vers ONTAP 9.17.1 ou l'initialisation d'un nouveau cluster ONTAP 9.17.1 ASA r2. Vous pouvez utiliser l'interface de ligne de commande (CLI) ONTAP pour augmenter ou réduire la période d'évaluation par défaut en fonction de vos besoins opérationnels.


NOTE: Vous ne pouvez pas revenir à ONTAP 9.17.1 sur votre système ASA r2 une fois le rééquilibrage automatique de la charge de travail activé.

.Étapes
. Vérifiez le nombre de jours restant dans la période d'évaluation :
+
[source, cli]
----
placement rebalance config show -fields evaluation-window
----
. Modifier la période d'évaluation du rééquilibrage :
+
[source, cli]
----
placement rebalance config modify -evaluation-window <number_of_evaluation_days>
----
+
L'exemple suivant définit la période d'évaluation restante à 10 jours.

+
[listing]
----
placement rebalance config modify -evaluation-window 10
----




== Modifier le paramètre de rééquilibrage automatique de la charge de travail

Le rééquilibrage automatique des charges de travail est activé par défaut 14 jours après la mise à niveau vers ONTAP 9.17.1 ou l'initialisation d'un nouveau cluster ONTAP 9.17.1 ASA r2. Vous pouvez modifier le paramètre par défaut pour désactiver le rééquilibrage automatique des charges de travail ou le définir sur un état consultatif afin de signaler les charges de travail déséquilibrées sans les déplacer automatiquement.

.Étape
. Vérifiez le mode de rééquilibrage actuellement défini sur vos nœuds :
+
[source, cli]
----
placement rebalance config show -fields mode
----
. Modifier le paramètre de rééquilibrage automatique de la charge de travail :
+
[source, cli]
----
placement rebalance config modify -mode <disabled|advisory|automated>
----
. Vérifiez que le mode de rééquilibrage est modifié :
+
[source, cli]
----
placement rebalance config show -fields mode
----




== Déclencher manuellement le rééquilibrage de la charge de travail

Si vous avez désactivé le rééquilibrage automatique des charges de travail, vous pouvez toujours déclencher un rééquilibrage manuel. Ceci est utile si vous souhaitez rééquilibrer les charges de travail après une période d'ajustements manuels ou si vous avez défini le mode de rééquilibrage sur « conseillé » et souhaitez agir en fonction des indicateurs de charge de travail.

.Étapes
. Vérifiez le mode de rééquilibrage actuellement défini sur vos nœuds :
+
[source, cli]
----
placement rebalance config show -fields mode
----
. Si le mode de rééquilibrage n'est pas défini sur *advisory*, définissez-le sur *advisory* :
+
[source, cli]
----
placement rebalance config modify -mode advisory
----
. Déclencher manuellement un rééquilibrage de la charge de travail :
+
[source, cli]
----
balanced-placement rebalance execute
----
. Afficher l'état de l'opération de rééquilibrage :
+
[source, cli]
----
placement rebalance show-evaluation
----


.Et la suite ?
Si vous souhaitez définir le mode de rééquilibrage sur *automatisé* ou *désactivé*, vous pouvez le faire en utilisant le  `placement rebalance config modify` commande.
