---
sidebar: sidebar 
permalink: administer/revert-ontap.html 
keywords: update, revert, ontap, asa r2 
summary: 'Les restaurations du logiciel ONTAP pour les systèmes ASA r2 suivent le même processus que les restaurations pour les autres systèmes ONTAP . La restauration d"un cluster ONTAP est perturbatrice.' 
---
= Rétablir ONTAP sur les systèmes de stockage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les restaurations du logiciel ONTAP pour les systèmes ASA r2 suivent le même processus que les restaurations pour les autres systèmes ONTAP .

La restauration d'un cluster ONTAP est une opération perturbatrice. Vous devez mettre le cluster hors ligne pendant toute la durée de la restauration. Vous ne devez pas restaurer un cluster de production sans l'assistance du support technique. Vous pouvez restaurer un cluster neuf ou de test sans assistance. Si la restauration d'un système neuf ou de test échoue, ou si elle réussit mais que les performances du cluster dans votre environnement de production ne vous satisfont pas, vous devez contacter le support technique pour obtenir de l'assistance.

Consultez link:https://docs.netapp.com/us-en/ontap/revert/task_reverting_an_ontap_cluster.html["Rétablir un cluster ONTAP"] pour la procédure de rétablissement complète.



[[revert-requirements-for-asa-r2-systems]]
== Rétablir les exigences pour les systèmes ASA r2

Certaines configurations de cluster ASA r2 nécessitent que vous preniez des mesures spécifiques avant de commencer une restauration du logiciel ONTAP .



[[reverting-from-ontap-9-17-1]]
=== Retour à ONTAP 9.17.1

Si vous revenez à ONTAP 9.17.1 sur un système ASA r2, vous devez effectuer les actions suivantes avant de commencer la restauration :


NOTE: link:space-balancing.html["équilibrage dynamique de l'espace"]est activé par défaut 14 jours après la mise à niveau vers ONTAP 9.17.1 ou l'initialisation d'un nouveau cluster ONTAP 9.17.1 ASA r2.  Vous ne pouvez pas revenir à la version ONTAP 9.17.1 sur votre système ASA r2 après l'activation de l'équilibrage dynamique de l'espace.

[cols="2"]
|===
| Si vous avez... | Avant de revenir en arrière, vous devriez... 


| Groupes de cohérence hiérarchique dans une relation de synchronisation active SnapMirror | link:../data-protection/snapmirror-active-sync-delete-relationship.html["Supprimer la relation de synchronisation active SnapMirror"]. 


| Relations d'importation actives | Supprimez les relations d'importation actives. link:../install-setup/set-up-data-access.html#migrate-data-from-a-third-party-storage-system["Découvrez les relations d'importation"]. 


| Protection anti-ransomware activée | link:../secure-data/pause-resume-anti-ransomware-protection.html["Suspendre la protection anti-ransomware"]. 
|===