---
sidebar: sidebar 
permalink: administer/space-balancing.html 
keywords: capacity, space, rebalancing, balanced, placement, balance, asa r2 
summary: 'Vous devrez peut-être renommer un nœud pour l"aligner sur les conventions de nommage de votre entreprise ou pour d"autres raisons d"ordre administratif.' 
---
= Découvrez comment équilibrer la capacité ONTAP dans un cluster ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour les systèmes ASA r2, ONTAP utilise le _placement équilibré_ pour placer automatiquement les unités de stockage nouvellement créées dans la meilleure zone de disponibilité de stockage afin d'obtenir des performances optimales et une utilisation équilibrée du stockage.  Si vous utilisez ONTAP 9.17.1 ou une version ultérieure, l'espace consommé par les unités de stockage existantes est équilibré à l'aide de l'équilibrage dynamique de l'espace.  Si vous utilisez ONTAP 9.16.1, l'espace consommé par les unités de stockage existantes est équilibré à l'aide d'un rééquilibrage de charge de travail basé sur la copie.

[cols="2"]
|===
| Fonction | Soutenu dans... 


| Placement équilibré | ONTAP 9.16.1 et versions ultérieures 


| Équilibrage dynamique de l'espace | ONTAP 9.17.1 et versions ultérieures 


| Rééquilibrage de la charge de travail basé sur la copie | ONTAP 9.16.1 uniquement 
|===
.Placement équilibré
Grâce au placement équilibré, les unités de stockage nouvellement créées sont automatiquement placées dans la zone de disponibilité de stockage optimale pour des performances optimales et une utilisation équilibrée du stockage.  Le placement équilibré est activé par défaut dans ONTAP 9.16.1 et versions ultérieures.

.Équilibrage dynamique de l'espace
Grâce à l'équilibrage dynamique de l'espace, ONTAP surveille activement la quantité d'espace libre dans le cluster et déplace automatiquement les unités de stockage au sein des zones de disponibilité de stockage afin de maintenir une utilisation équilibrée de l'espace.  Un avertissement EMS est automatiquement émis si le taux d'utilisation de la capacité à l'échelle du cluster atteint 80 %, et une alerte EMS est automatiquement émise si ce taux atteint 90 %.

L'équilibrage dynamique de l'espace est activé par défaut 14 jours après la mise à niveau ou l'installation ONTAP 9.17.1 ou version ultérieure.  Si vous devez modifier la période d'activation par défaut de 14 jours, contactez le support NetApp .  Il est impossible de revenir à la version ONTAP 9.17.1 une fois l'équilibrage dynamique de l'espace activé.

L'équilibrage dynamique de l'espace fonctionne soit en _mode normal_, soit en _mode espace réduit_, en fonction de la moyenne globale de l'espace libre dans tous les nœuds du cluster (moyenne globale).

* *Mode normal*
+
En mode normal, ONTAP vérifie toutes les trois minutes si un équilibrage dynamique de l'espace est nécessaire.  L'équilibrage dynamique de l'espace fonctionne en mode normal lorsque les conditions suivantes sont réunies :

+
** La moyenne mondiale d'espace libre est de 10 % ou plus.
** Au moins un nœud du cluster dispose de plus d'espace libre que la moyenne globale.
** Au moins un nœud du cluster dispose de 20 % d'espace libre en moins que la moyenne mondiale.


* *Mode espace réduit*
+
En mode espace réduit, ONTAP vérifie chaque minute si un équilibrage dynamique de l'espace est nécessaire.  L'équilibrage dynamique de l'espace fonctionne en mode espace réduit lorsque les conditions suivantes sont réunies :

+
** La moyenne mondiale d'espace libre est inférieure à 10 %.
** Au moins un nœud du cluster dispose de plus d'espace libre que la moyenne globale.
** Au moins un nœud du cluster dispose de moins d'espace libre que la moyenne globale.




.Rééquilibrage de la charge de travail basé sur la copie
Avec le rééquilibrage de charge de travail basé sur la copie, si un déséquilibre dans l'utilisation du stockage se produit au sein des zones de disponibilité du stockage, ONTAP copie automatiquement l'unité de stockage à l'origine du déséquilibre vers une zone de disponibilité du stockage disposant d'un espace libre plus important.  Si l'espace libre est insuffisant dans la zone de disponibilité du stockage de destination, ONTAP n'effectue aucune action d'équilibrage.  Le rééquilibrage de charge de travail basé sur la copie s'applique uniquement au système ASA r2 exécutant ONTAP 9.16.1, et il est activé par défaut sur ces systèmes.  Dans ONTAP 9.17.1 et versions ultérieures, il est remplacé par l'équilibrage dynamique de l'espace.

Si vous devez modifier les paramètres par défaut du rééquilibrage de charge de travail basé sur la copie, contactez le support NetApp .
