---
sidebar: sidebar 
permalink: administer/upgrade-ontap.html 
keywords: update, firmware, system files, automatic updates, automated updates, asa r2, disable, 
summary: Les mises à niveau du logiciel ONTAP pour les systèmes ASA r2 suivent le même processus que les mises à niveau pour les autres systèmes ONTAP .  Lorsque vous mettez à niveau votre logiciel ONTAP sur votre système ASA r2, vous pouvez profiter de fonctionnalités ONTAP nouvelles et améliorées. 
---
= Mise à niveau de ONTAP sur les systèmes de stockage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous mettez à niveau votre logiciel ONTAP sur votre système ASA r2, vous pouvez bénéficier des nouvelles fonctionnalités ONTAP améliorées pour réduire les coûts, accélérer les charges de travail stratégiques, améliorer la sécurité et étendre la portée de la protection des données disponible pour votre entreprise.

Les mises à niveau du logiciel ONTAP pour les systèmes ASA r2 suivent le même processus que celles des autres systèmes ONTAP. Il est recommandé de commencer par link:https://docs.netapp.com/us-en/ontap/upgrade/create-upgrade-plan.html["Préparation de votre mise à niveau avec Upgrade Advisor dans Active IQ Digital Advisor ou Upgrade Health Checker"].

Après avoir préparé votre mise à niveau, il est recommandé d'effectuer les mises à niveau à l'aide de link:https://docs.netapp.com/us-en/ontap/upgrade/task_upgrade_andu_sm.html["Mise à niveau automatisée sans interruption (ANDU) depuis System Manager"]. ANDU exploite la technologie de basculement haute disponibilité d'ONTAP pour assurer le service des données sans interruption lors de la mise à niveau.

En savoir plus sur link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["Mises à niveau du logiciel ONTAP"].
