---
sidebar: sidebar 
permalink: get-started/learn-about.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, learn more, learn about, get started 
summary: 'Les systèmes ASA r2 (ASA A1K, A90, A70, A50, A30, A20, C30) offrent une solution matérielle et logicielle unifiée pour une expérience simplifiée pour les clients SAN uniquement.' 
searchtitle: En savoir plus sur les systèmes ASA A1K, A90, A70, A50, A30 A20 et C30 
---
= En savoir plus sur les systèmes de stockage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes NetApp ASA r2 apportent une solution matérielle et logicielle unifiée qui simplifie l'expérience et répond parfaitement aux besoins des clients SAN.

Les éléments suivants sont classés comme systèmes ASA r2 :

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30


Les systèmes ASA r2 prennent en charge tous les protocoles SAN (iSCSI, FC, NVMe/FC, NVMe/TCP).  Les protocoles iSCSI, FC, NVMe/FC et NVMe/TCP prennent en charge l'architecture active-active symétrique pour le multivoie afin que tous les chemins entre les hôtes et le stockage soient actifs/optimisés.  Les protocoles iSCSI et NVMe/TCP prennent en charge la connexion directe entre les hôtes et le stockage.  Pour les protocoles Fibre Channel et NVMe/FC, la connexion directe n'est pas prise en charge.

Sur un système ASA r2, le logiciel ONTAP et System Manager sont optimisés pour prendre en charge les fonctionnalités SAN essentielles tout en supprimant les fonctionnalités et fonctionnalités non prises en charge dans les environnements SAN.

Les systèmes ASA r2 introduisent l'utilisation d'unités de stockage avec groupes de cohérence :

* Une _unité de stockage_ permet à vos hôtes SAN de disposer de l'espace de stockage pour les opérations de données. Une unité de stockage désigne une LUN pour les hôtes SCSI ou un namespace NVMe pour les hôtes NVMe.
* _Un groupe de cohérence_ est un ensemble d'unités de stockage gérées comme une seule unité.


Les systèmes ASA r2 utilisent des unités de stockage avec des groupes de cohérence pour simplifier la gestion du stockage et la protection des données.  Par exemple, supposons que vous disposez d’une base de données composée de 10 unités de stockage dans un groupe de cohérence et que vous devez sauvegarder l’intégralité de la base de données.  Au lieu de sauvegarder chaque unité de stockage individuellement, vous pouvez protéger l’intégralité de la base de données en sauvegardant le groupe de cohérence.

Pour protéger vos données contre les attaques malveillantes telles que le vol ou les rançongiciels, les systèmes ASA r2 prennent en charge un gestionnaire de clés intégré, un chiffrement double couche, une authentification multifacteur et une vérification multi-administrateur. Les instantanés inviolables sont également pris en charge sur les systèmes ASA r2 secondaires.

Les systèmes ASA r2 ne prennent pas en charge le mixage de clusters avec les systèmes ASA, AFF ou FAS .

.Pour en savoir plus
* Pour en savoir plus sur la prise en charge et les limites des systèmes ASA r2link:https://hwu.netapp.com/["NetApp Hardware Universe"^], consultez le .
* En savoir plus sur link:../learn-more/hardware-comparison.html["Les systèmes ASA r2 par rapport aux systèmes ASA"].
* En savoir plus sur link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"^]le .

