---
sidebar: sidebar 
permalink: get-started/learn-about.html 
keywords: asa r2, asa a1k, asa 70, asa 90 
summary: 'Les systèmes ASA r2 (ASA A1K, ASA A70 et ASA A90) proposent une solution matérielle et logicielle unifiée qui simplifie l"expérience des clients SAN uniquement.' 
searchtitle: En savoir plus sur les systèmes de stockage ASA A1K, ASA A70 et ASA A90 
---
= En savoir plus sur les systèmes de stockage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes NetApp ASA r2 (ASA A1K, ASA A70 et ASA A90) proposent une solution matérielle et logicielle unifiée qui simplifie l'expérience en fonction des besoins des clients qui utilisent exclusivement SAN.

Les systèmes ASA r2 prennent en charge tous les protocoles SAN (iSCSI, FC, NVMe/FC, NVMe/TCP) sur un déploiement de paire haute disponibilité unique. Les protocoles SCSI (iSCSI et FC) utilisent une architecture actif-actif symétrique pour les chemins d'accès multiples, de sorte que tous les chemins entre les hôtes et le stockage soient actifs/optimisés. Les protocoles NVMe prennent en charge les chemins directs entre les hôtes et le stockage.

Sur un système ASA r2, le logiciel ONTAP et System Manager sont optimisés pour prendre en charge les fonctionnalités SAN essentielles tout en supprimant les fonctionnalités et fonctionnalités non prises en charge dans les environnements SAN.

Les systèmes ASA r2 introduisent l'utilisation d'unités de stockage avec groupes de cohérence :

* Une _unité de stockage_ permet à vos hôtes SAN de disposer de l'espace de stockage pour les opérations de données. Une unité de stockage désigne une LUN pour les hôtes SCSI ou un namespace NVMe pour les hôtes NVMe.
* _Un groupe de cohérence_ est un ensemble d'unités de stockage gérées comme une seule unité.


Les systèmes ASA r2 utilisent des unités de stockage et des groupes de cohérence pour simplifier la gestion du stockage et la protection des données. Supposons par exemple que vous disposez d'une base de données constituée de 10 unités de stockage dans un groupe de cohérence et que vous devez sauvegarder l'ensemble de la base de données. Au lieu de sauvegarder chaque unité de stockage individuellement, vous pouvez protéger l'ensemble de la base de données en sauvegardant le groupe de cohérence.

Pour vous aider à sécuriser vos données contre les attaques malveillantes, telles que le vol ou les ransomware, les systèmes ASA r2 prennent en charge un gestionnaire de clés intégré, un chiffrement double couche, des copies Snapshot inviolables, une authentification multifacteur et la vérification multiadministrateur.

Les systèmes ASA r2 ne prennent pas en charge la combinaison de clusters avec les systèmes ASA, AFF ou FAS actuels.

.Pour en savoir plus
* Pour en savoir plus sur la prise en charge et les limites des systèmes ASA r2link:https://hwu.netapp.com/["NetApp Hardware Universe"^], consultez le .
* En savoir plus sur link:../learn-more/hardware-comparison.html["Nouveaux systèmes ASA r2 par rapport aux systèmes ASA"].
* En savoir plus sur link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"]le .

