---
sidebar: sidebar 
permalink: data-protection/manage-consistency-groups.html 
keywords: consistency groups, snapshots, data protection, protect data, add, remove, delete, storage units, lun, namespace, increase capacity 
summary: 'Utilisez les groupes de cohérence pour effectuer différentes actions simultanément sur plusieurs unités de stockage au lieu d"effectuer des actions individuelles sur chaque unité.' 
---
= En savoir plus sur les groupes de cohérence ONTAP sur les systèmes de stockage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un groupe de cohérence est un ensemble d’unités de stockage gérées comme une seule unité.  Utilisez des groupes de cohérence pour une gestion simplifiée du stockage.

Par exemple, supposons que vous disposez d’une base de données composée de 10 unités de stockage dans un groupe de cohérence et que vous devez sauvegarder l’intégralité de la base de données. Au lieu de sauvegarder chaque unité de stockage, vous pouvez sauvegarder l’intégralité de la base de données en ajoutant simplement une protection des données de snapshot au groupe de cohérence.  La sauvegarde des unités de stockage en tant que groupe de cohérence plutôt qu'individuellement fournit également une sauvegarde cohérente de toutes les unités, tandis que la sauvegarde des unités individuellement peut potentiellement créer des incohérences.

À partir d' ONTAP 9.16.1, vous pouvez utiliser System Manager pour créer des groupes de cohérence hiérarchiques sur votre système ASA r2.  Dans une structure hiérarchique, un ou plusieurs groupes de cohérence sont configurés comme enfants sous un groupe de cohérence parent.

Les groupes de cohérence hiérarchiques vous permettent d'appliquer des règles de snapshot individuelles à chaque groupe de cohérence enfant et de répliquer les snapshots de tous les groupes de cohérence enfant sur un cluster distant en tant qu'unité unique en répliquant le parent. Cela simplifie la protection et la gestion des données pour les structures de données complexes. Supposons par exemple que vous créez le groupe de cohérence parent appelé `SVM1_app` qui contient deux groupes de cohérence enfant : `SVM1app_data` pour les données d'application et `SVM1app_logs` pour les journaux d'application. Des instantanés de `SVM1app_data` sont pris toutes les 15 minutes et des instantanés de `SVM1app_logs` sont pris toutes les heures. Le groupe de cohérence parent, `SVM1_app,` dispose d'une règle SnapMirror qui réplique les snapshots de `SVM1app_data` et `SVM1app_logs` sur un cluster distant toutes les 24 heures. Le groupe de cohérence parent `SVM1_app` est géré comme une seule unité et les groupes de cohérence enfant sont gérés comme des unités distinctes.



== Groupes de cohérence dans les relations de réplication

À partir d' ONTAP 9.17.1, vous pouvez apporter les modifications de géométrie suivantes aux groupes de cohérence dans une relation de réplication asynchrone ou dans une relation de synchronisation active SnapMirror sans interrompre ou supprimer la relation.  Lorsqu'un changement de géométrie se produit sur le groupe de cohérence principal, le changement est répliqué sur le groupe de cohérence secondaire.

* link:manage-consistency-groups-add-remove-storage-units.html["Modifier la taille d'une unité de stockage"]en ajoutant ou en supprimant des unités de stockage.
* link:manage-hierarchical-consistency-groups.html#promote-an-existing-consistency-group-into-a-parent-consistency-group["Promouvoir un groupe de cohérence unique"]à un groupe de cohérence parent.
* link:manage-hierarchical-consistency-groups.html#demote-a-parent-consistency-group-to-a-single-consistency-group["Rétrograder un groupe de cohérence parent"]à un seul groupe de cohérence.
* link:manage-hierarchical-consistency-groups.html#detach-a-child-consistency-group-from-a-parent-consistency-group["Détacher un groupe de cohérence enfant"]d'un groupe de cohérence parent.
* link:manage-hierarchical-consistency-groups.html#create-a-child-consistency-group["Créer un groupe de cohérence enfant"]en utilisant un groupe de cohérence existant.


Dans ONTAP 9.16.1, vous devezlink:snapmirror-active-sync-break-relationship.html["rompre la relation de réplication asynchrone"] etlink:snapmirror-active-sync-delete-relationship.html["supprimer la relation de synchronisation active SnapMirror"] avant d'apporter des modifications géométriques au groupe de cohérence.
