---
sidebar: sidebar 
permalink: release-notes/changes-to-limits-defaults.html 
keywords: release notes, changes, updates, defaults, limits, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30 
summary: En savoir plus sur les modifications des limites et des valeurs par défaut affectant les systèmes ASA r2. 
---
= Modifications des limites ONTAP et des valeurs par défaut affectant les systèmes ASA r2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En savoir plus sur les modifications des limites et des valeurs par défaut affectant les systèmes ASA r2. NetApp s'efforce d'aider ses clients à comprendre les valeurs par défaut les plus importantes et à limiter les modifications apportées à chaque version de ONTAP.



== Modifications des limites ONTAP

[cols="2,4,4"]
|===
| Fonction | Modification de limite | Modifié dans la version... 


| Machines virtuelles de stockage par cluster | Le nombre maximal de machines virtuelles de stockage prises en charge (VM) par paire HA passe de 32 à 256. | ONTAP 9.18.1 


| SnapMirror activ sync | La prise en charge de la synchronisation active SnapMirror est étendue des clusters à deux nœuds aux clusters à quatre nœuds. | ONTAP 9.18.1 


| Nœuds par cluster  a| 
Le nombre maximum de nœuds par cluster est passé de 2 à 12.


NOTE: Si vous exécutez ONTAP 9.16.1 avec plus de 2 nœuds dans un cluster, vous ne pouvez pas revenir à ONTAP 9.16.0.
| ONTAP 9.16.1 


| Unités de stockage | Le nombre maximal d'unités de stockage est augmenté de 2500 par paire haute disponibilité à 10,000 par paire haute disponibilité. | ONTAP 9.16.1 
|===